/**
 * Assembles dist/ — exactly the files that should be publicly served.
 *
 * The asset list is derived from what the pages actually reference, using the
 * same scanner as check-assets.mjs, rather than from a hand-maintained include
 * or ignore list. Two earlier attempts at pattern matching got this wrong in
 * both directions: they shipped the 10.7 MB source video and the logo masters,
 * while a blunter rule would have dropped leaf-tile.png, which CSS genuinely
 * needs as an image-set() fallback.
 *
 * No dependencies: node builtins only, so a deploy does not need `npm install`
 * to have succeeded.
 *
 * Usage: npm run dist
 */
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/assets.mjs';
import { entryFiles, scanReferences } from './lib/refs.mjs';

const DIST = path.join(ROOT, 'dist');

/** Documents served directly, plus the small static files at the root. */
const ROOT_FILES = [
  ...fs.readdirSync(ROOT).filter((f) => f.endsWith('.html')),
  'robots.txt',
  'sitemap.xml',
  'site.webmanifest',
];

const { referenced, missing } = scanReferences(entryFiles());

if (missing.length) {
  console.error(`\nrefusing to build dist/: ${missing.length} reference(s) do not resolve`);
  for (const m of missing) console.error(`  ${m.file}:${m.line}  ->  ${m.ref}`);
  process.exit(1);
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

let files = 0;
let bytes = 0;

function copy(rel) {
  const src = path.join(ROOT, rel);
  if (!fs.existsSync(src) || fs.statSync(src).isDirectory()) return;
  const dest = path.join(DIST, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  files++;
  bytes += fs.statSync(src).size;
}

for (const f of ROOT_FILES) copy(f);
for (const rel of referenced.keys()) copy(rel);

/**
 * Cache headers. Generated variants carry their width in the filename and are
 * replaced rather than edited, so they can be cached immutably. HTML must not
 * be, or a deploy would not become visible until caches expired.
 */
const HEADERS = `# Generated by scripts/build-dist.mjs

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/css/*
  Cache-Control: public, max-age=3600

/js/*
  Cache-Control: public, max-age=3600

/*.html
  Cache-Control: public, max-age=0, must-revalidate

/
  Cache-Control: public, max-age=0, must-revalidate
`;
fs.writeFileSync(path.join(DIST, '_headers'), HEADERS);
files++;

console.log(`dist/  ${files} files, ${(bytes / 1048576).toFixed(2)} MB`);
