/**
 * Downloads the self-hosted webfonts and generates css/fonts.css.
 *
 * The site previously pulled three families from fonts.googleapis.com +
 * fonts.gstatic.com on every page, costing two extra DNS/TLS handshakes and a
 * render-blocking stylesheet before any text could paint. Self-hosting removes
 * both hosts.
 *
 * Only the `latin` subset is kept. Google's API also returns latin-ext,
 * cyrillic, cyrillic-ext, greek and vietnamese cuts, none of which this site
 * has any content for.
 *
 * All three families are libre-licensed, so redistribution is permitted:
 *   Cormorant Garamond - SIL Open Font License 1.1
 *   DM Sans            - SIL Open Font License 1.1
 *   JetBrains Mono     - SIL Open Font License 1.1
 * See assets/fonts/OFL.txt.
 *
 * Variable cuts are requested rather than one static file per weight: the site
 * uses four DM Sans weights, which as static faces cost 4 x 36 KB but as a
 * single variable file cost 61 KB.
 *
 * DM Sans italic is deliberately NOT fetched. Its variable cut is 74 KB and the
 * only rule that wanted it was `.dish-card__local` at 11.5px, where the
 * browser's synthetic oblique is indistinguishable. Cormorant italic IS kept -
 * it carries the hero headline emphasis, which is a prominent design element.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/assets.mjs';

const FONT_DIR = path.join(ROOT, 'assets', 'fonts');
const CSS_OUT = path.join(ROOT, 'css', 'fonts.css');

const API = 'https://fonts.googleapis.com/css2?' + [
  'family=Cormorant+Garamond:ital,wght@0,400..700;1,400..700',
  'family=DM+Sans:opsz,wght@9..40,400..700',
  'family=JetBrains+Mono:wght@400..500',
  'display=swap',
].join('&');

// Google's CSS API varies its response by User-Agent; a modern browser UA is
// what returns woff2 rather than legacy formats.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

fs.mkdirSync(FONT_DIR, { recursive: true });

const res = await fetch(API, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`font CSS fetch failed: HTTP ${res.status}`);
const css = await res.text();

/** Split the response into `/* subset *\/ @font-face { ... }` records. */
function parseFaces(text) {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  for (const m of text.matchAll(re)) {
    const [, subset, block] = m;
    const get = (prop) => (block.match(new RegExp(prop + ':\\s*([^;]+);')) || [])[1]?.trim();
    const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!url) continue;
    out.push({
      subset,
      family: get('font-family')?.replace(/['"]/g, ''),
      style: get('font-style') || 'normal',
      weight: get('font-weight') || '400',
      unicodeRange: get('unicode-range'),
      url,
    });
  }
  return out;
}

const faces = parseFaces(css).filter((f) => f.subset === 'latin');
if (!faces.length) throw new Error('no latin faces parsed from font CSS');

/** `Cormorant Garamond` + weight `400 700` italic -> `cormorant-garamond-var-italic.woff2` */
const slug = (f) => {
  const family = f.family.toLowerCase().replace(/\s+/g, '-');
  const weight = /\s/.test(f.weight) ? 'var' : f.weight;
  return `${family}-${weight}${f.style === 'italic' ? '-italic' : ''}.woff2`;
};

let bytes = 0;
const blocks = [];

for (const f of faces) {
  const file = slug(f);
  const dest = path.join(FONT_DIR, file);
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  fs.writeFileSync(dest, buf);
  bytes += buf.length;
  console.log(`${file.padEnd(34)} ${(buf.length / 1024).toFixed(1).padStart(6)} KB`);

  blocks.push(
    `@font-face {\n` +
    `  font-family: '${f.family}';\n` +
    `  font-style: ${f.style};\n` +
    `  font-weight: ${f.weight};\n` +
    `  font-display: swap;\n` +
    `  src: url('../assets/fonts/${file}') format('woff2');\n` +
    `  unicode-range: ${f.unicodeRange};\n` +
    `}`
  );
}

const header =
  `/* ============================================================\n` +
  `   Self-hosted webfonts - latin subset only.\n` +
  `   GENERATED by scripts/fetch-fonts.mjs; do not edit by hand.\n` +
  `   All three families are SIL OFL 1.1; see assets/fonts/OFL.txt.\n` +
  `   ============================================================ */\n\n`;

fs.writeFileSync(CSS_OUT, header + blocks.join('\n\n') + '\n');

console.log('-'.repeat(48));
console.log(`${faces.length} faces, ${(bytes / 1024).toFixed(1)} KB total`);
console.log(`wrote css/fonts.css`);
